name: test_action

on: [push]

jobs:
  test_set_comp:
    runs-on: ubuntu-latest
    steps:
    - name: Setup TeXLive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-basic
          graphicx
          hyperref
          multicol
          anysize
          fontspec
          ctex
          tabularx
          chinese-jfm
          tex-gyre-bonum
          noto
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Concat & Compile
      run: |
        python concat.py testcase
        python checkout.py testcase
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: ./output/*.pdf
    - name: Upload Outputs
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: ./output